<a href="https://colab.research.google.com/github/msrahulvarma/RahulVarma_INFO5731_Fall2023/blob/main/Muppalla_exercise_03_11633662.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The third In-class-exercise (due on 11:59 PM 10/08/2023, 40 points in total)

The purpose of this exercise is to understand text representation.

Question 1 (10 points): Describe an interesting text classification or text mining task and explain what kind of features might be useful for you to build the machine learning model. List your features and explain why these features might be helpful. You need to list at least five different types of features.

In [ ]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Text mining task: Classifying Food Reviews into Categories (e.g., Taste, Presentation, Value for Money, Service, Ambiance)
Explanation: Given a food review, determine which category or categories it primarily pertains to. For example, a review saying "The steak was juicy and cooked to perfection" primarily pertains to 'Taste'.


Of course! Here are five of the features presented in a more concise format with side headings:

1. Bag-of-Words (BoW) specific to Food Terminology
Represents text by the frequency of food-specific words, without considering their order or structure. Words like "delicious" or "tasty" can indicate the 'Taste' category, while terms like "dimly-lit" or "noisy" might pertain to the 'Ambiance' of a restaurant. The choice of words in a review can often give direct insights into the aspects of a dining experience that stood out to the reviewer.

2. TF-IDF with Food-Related Vocabulary
This approach weighs terms in a review based on their importance within the context of food reviews. By giving more weight to terms that are unique to specific categories, this method can emphasize words that are particularly descriptive of categories like 'Service', such as "attentive" or "slow". It's a way to filter out common words and focus on those that are more informative.

3. N-grams
N-grams capture sequences of 'N' adjacent words in a review. For example, a 2-gram from the review "The waiter was incredibly rude" would produce sequences like "The waiter" or "was incredibly". This method can be particularly useful as some sentiments or descriptions are best captured by combinations of words rather than individual terms. Phrases like "worth every penny" can directly hint at the 'Value for Money' category.

4. Sentiment Analysis
By measuring the sentiment of a review or parts of it, we can gain insights into the reviewer's feelings about specific aspects of their experience. For instance, a highly negative sentiment combined with words related to waiting or service might suggest dissatisfaction with the 'Service' at the establishment. Sentiment analysis provides a lens to view the emotional content of reviews.

5. Document Structure and Length
The overall structure and length of a review can also be telling. Longer, detailed reviews might encompass feedback on multiple aspects of a dining experience, from 'Taste' to 'Ambiance'. In contrast, a short and to-the-point review might focus on a singular standout aspect, be it positive or negative. The way a reviewer structures their feedback can offer clues about which elements of their experience were most memorable.



'''

'\nText mining task: Classifying Food Reviews into Categories (e.g., Taste, Presentation, Value for Money, Service, Ambiance)\nExplanation: Given a food review, determine which category or categories it primarily pertains to. For example, a review saying "The steak was juicy and cooked to perfection" primarily pertains to \'Taste\'.\n\n\nOf course! Here are five of the features presented in a more concise format with side headings:\n\n1. Bag-of-Words (BoW) specific to Food Terminology\nRepresents text by the frequency of food-specific words, without considering their order or structure. Words like "delicious" or "tasty" can indicate the \'Taste\' category, while terms like "dimly-lit" or "noisy" might pertain to the \'Ambiance\' of a restaurant. The choice of words in a review can often give direct insights into the aspects of a dining experience that stood out to the reviewer.\n\n2. TF-IDF with Food-Related Vocabulary\nThis approach weighs terms in a review based on their importance w

Question 2 (10 points): Write python code to extract these features you discussed above. You can collect a few sample text data for the feature extraction.

In [1]:
# You code here (Please add comments in the code):
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from textblob import TextBlob

# Sample reviews
reviews = [
    "The steak was juicy and cooked to perfection. Best I've ever had.",
    "I really loved the dimly-lit atmosphere. It gave the place a cozy feel.",
    "Honestly, for the price I paid, the food was subpar. Not worth it.",
    "The waiter was incredibly rude. Ruined the whole experience for me.",
    "The presentation of the dish was a visual delight! Looked too good to eat.",
    "The background music was way too loud. Couldn't even have a conversation.",
    "The service was attentive and quick. Our glasses were never empty.",
    "For such a high-end place, the ambiance was lacking. Felt very generic.",
    "Flavors were on point! The dessert was the cherry on top.",
    "We had to wait for 30 minutes even with a reservation. Not coming back."
]

# 1. Bag-of-Words (BoW) specific to Food Terminology
# Predefined set of food-related terms
food_related_terms = ['steak', 'juicy', 'cooked', 'atmosphere', 'price', 'food', 'waiter', 'presentation', 'dish', 'music', 'service', 'ambiance', 'flavors', 'dessert', 'wait', 'reservation']
# Create a vectorizer and transform the reviews into a BoW matrix
vectorizer_bow = CountVectorizer(vocabulary=food_related_terms)
bow_matrix = vectorizer_bow.fit_transform(reviews).toarray()

# 2. TF-IDF with Food-Related Vocabulary
# Create a TF-IDF vectorizer using the predefined food-related terms and transform the reviews
vectorizer_tfidf = TfidfVectorizer(vocabulary=food_related_terms)
tfidf_matrix = vectorizer_tfidf.fit_transform(reviews).toarray()

# 3. N-grams
# Create a vectorizer to capture unigrams, bigrams, and trigrams, then transform the reviews
vectorizer_ngram = CountVectorizer(ngram_range=(1, 3))
ngram_matrix = vectorizer_ngram.fit_transform(reviews).toarray()

# 4. Sentiment Analysis
# Compute the sentiment score for each review using TextBlob
sentiments = [TextBlob(review).sentiment.polarity for review in reviews]

# 5. Document Structure and Length
# Compute the word count for each review
lengths = [len(review.split()) for review in reviews]


In [2]:
print("\n1. Bag-of-Words (BoW) specific to Food Terminology:")
print(bow_matrix)

print("\n2. TF-IDF with Food-Related Vocabulary:")
print(tfidf_matrix)

print("\n3. N-grams:")
print(ngram_matrix)

print("\n4. Sentiment Analysis:")
print(sentiments)

print("\n5. Document Structure and Length:")
print(lengths)


1. Bag-of-Words (BoW) specific to Food Terminology:
[[1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1]]

2. TF-IDF with Food-Related Vocabulary:
[[0.57735027 0.57735027 0.57735027 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         1.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.70710678 0.70710678
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         

Question 3 (10 points): Use any of the feature selection methods mentioned in this paper "Deng, X., Li, Y., Weng, J., & Zhang, J. (2019). Feature selection for text classification: A review. Multimedia Tools & Applications, 78(3)."

Select the most important features you extracted above, rank the features based on their importance in the descending order.

In [3]:
from sklearn.feature_selection import mutual_info_classif
from sklearn.feature_extraction.text import CountVectorizer

# Sample data
texts = [
    "The steak was juicy and cooked to perfection. Best I've ever had.",
    "I really loved the dimly-lit atmosphere. It gave the place a cozy feel.",
    "Honestly, for the price I paid, the food was subpar. Not worth it.",
    "The waiter was incredibly rude. Ruined the whole experience for me.",
    "The presentation of the dish was a visual delight! Looked too good to eat.",
    "The background music was way too loud. Couldn't even have a conversation.",
    "The service was attentive and quick. Our glasses were never empty.",
    "For such a high-end place, the ambiance was lacking. Felt very generic.",
    "Flavors were on point! The dessert was the cherry on top.",
    "We had to wait for 30 minutes even with a reservation. Not coming back."
]

# Labels based on sentiment (1 for positive, 0 for negative)
labels = [1, 1, 0, 0, 1, 0, 1, 0, 1, 0]

# Convert texts to matrix of token counts
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texts)

# Compute Mutual Information
mi = mutual_info_classif(X, labels, discrete_features=True)

# Pairing features with their MI scores
feature_mi = dict(zip(vectorizer.get_feature_names_out(), mi))

# Sorting features based on MI scores in descending order
sorted_feature_mi = sorted(feature_mi.items(), key=lambda x: x[1], reverse=True)

# Displaying the ranked features
for rank, (feature, score) in enumerate(sorted_feature_mi, 1):
    print(f"{rank}. {feature}: {score:.4f}")


1. for: 0.4228
2. and: 0.1639
3. even: 0.1639
4. not: 0.1639
5. were: 0.1639
6. the: 0.0794
7. 30: 0.0749
8. ambiance: 0.0749
9. atmosphere: 0.0749
10. attentive: 0.0749
11. back: 0.0749
12. background: 0.0749
13. best: 0.0749
14. cherry: 0.0749
15. coming: 0.0749
16. conversation: 0.0749
17. cooked: 0.0749
18. couldn: 0.0749
19. cozy: 0.0749
20. delight: 0.0749
21. dessert: 0.0749
22. dimly: 0.0749
23. dish: 0.0749
24. eat: 0.0749
25. empty: 0.0749
26. end: 0.0749
27. ever: 0.0749
28. experience: 0.0749
29. feel: 0.0749
30. felt: 0.0749
31. flavors: 0.0749
32. food: 0.0749
33. gave: 0.0749
34. generic: 0.0749
35. glasses: 0.0749
36. good: 0.0749
37. have: 0.0749
38. high: 0.0749
39. honestly: 0.0749
40. incredibly: 0.0749
41. juicy: 0.0749
42. lacking: 0.0749
43. lit: 0.0749
44. looked: 0.0749
45. loud: 0.0749
46. loved: 0.0749
47. me: 0.0749
48. minutes: 0.0749
49. music: 0.0749
50. never: 0.0749
51. of: 0.0749
52. on: 0.0749
53. our: 0.0749
54. paid: 0.0749
55. perfection: 0.0749
56

In [ ]:
# You code here (Please add comments in the code):
'''
1. TF-IDF with Food Words:
It highlights special words in reviews. Words that appear often in one review but not in many others get more attention. This helps in figuring out the main topic of that particular review.

2. N-grams:
Groups of words, like "very tasty" or "too spicy", can tell us more than just single words alone. They help in understanding more about what the reviewer liked or disliked.

3. Word List (BoW) about Food:
This checks if certain food-related words are in the reviews. For instance, if words like "waiter" or "service" show up a lot, the review might be talking about the restaurant's staff.

4. Sentiment Analysis:
This tells us if the reviewer felt good, bad, or just okay about their experience. It's a quick way to gauge if the overall feedback is positive or negative.

5. Review Length:
The length of a review can give hints. Longer reviews might talk about various things like taste, service, and ambiance. Short reviews might be focusing on one main point, like how tasty the food was.
'''


Question 4 (10 points): Write python code to rank the text based on text similarity. Based on the text data you used for question 2, design a query to match the most relevant docments. Please use the BERT model to represent both your query and the text data, then calculate the cosine similarity between the query and each text in your data. Rank the similary with descending order.

In [10]:
# You code here (Please add comments in the code):
import torch
from transformers import BertTokenizer, BertModel
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

# Sample data
reviews = [
    "The steak was juicy and cooked to perfection. Best I've ever had.",
    "I really loved the dimly-lit atmosphere. It gave the place a cozy feel.",
    "Honestly, for the price I paid, the food was subpar. Not worth it.",
    "The waiter was incredibly rude. Ruined the whole experience for me.",
    "The presentation of the dish was a visual delight! Looked too good to eat.",
    "The background music was way too loud. Couldn't even have a conversation.",
    "The service was attentive and quick. Our glasses were never empty.",
    "For such a high-end place, the ambiance was lacking. Felt very generic.",
    "Flavors were on point! The dessert was the cherry on top.",
    "We had to wait for 30 minutes even with a reservation. Not coming back."
]

# Define the query
query = "I had a terrible experience because of the rude staff."

# Load BERT model and tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

# Function to get embeddings using BERT
def get_embedding(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=512)
    with torch.no_grad():
        outputs = model(**inputs)
    return outputs.last_hidden_state[:, 0, :].numpy()

# Get embeddings for reviews and query
review_embeddings = [get_embedding(review) for review in reviews]
query_embedding = get_embedding(query)

# Calculate cosine similarity
similarities = [cosine_similarity(query_embedding, review_embedding)[0][0] for review_embedding in review_embeddings]

# Rank reviews based on similarity scores
ranked_reviews = [reviews[i] for i in sorted(range(len(similarities)), key=lambda k: similarities[k], reverse=True)]

# Display ranked reviews
for idx, review in enumerate(ranked_reviews, 1):
    print(f"{idx}. {review}\n")



1. The waiter was incredibly rude. Ruined the whole experience for me.

2. The presentation of the dish was a visual delight! Looked too good to eat.

3. Honestly, for the price I paid, the food was subpar. Not worth it.

4. The background music was way too loud. Couldn't even have a conversation.

5. We had to wait for 30 minutes even with a reservation. Not coming back.

6. Flavors were on point! The dessert was the cherry on top.

7. I really loved the dimly-lit atmosphere. It gave the place a cozy feel.

8. The service was attentive and quick. Our glasses were never empty.

9. The steak was juicy and cooked to perfection. Best I've ever had.

10. For such a high-end place, the ambiance was lacking. Felt very generic.

